use adlister_db;

insert into users (id, password, email, username) values (1, 'f7e3349e0acc0808d55bc93fd3ccd21bae743911e6544800c6d91562f8b76e04', 'gserot0@about.me', 'dbourgourd0');
insert into users (id, password, email, username) values (2, '2bfb233b7bcec3aebf877fc995d4eee8f0662bce9af4e06658b3668ed5a55d8d', 'vfairhurst1@marriott.com', 'dvennings1');
insert into users (id, password, email, username) values (3, 'b813a7fef30105c699949cde2ed76567e5bab6e2bbfa59bff8061916c0252258', 'pdendle2@businessinsider.com', 'cchoulerton2');
insert into users (id, password, email, username) values (4, '6a41fad7bc295643c14a810d9ce901c3eea2edccd85c6e21700d849a62eeb4ce', 'sstollsteimer3@unc.edu', 'mjoney3');
insert into users (id, password, email, username) values (5, '3261670d30f83cf9fcbd73587357ec52decc52828ca13d16ea7e73272d41f5f9', 'ndolbey4@timesonline.co.uk', 'bcruickshanks4');
insert into users (id, password, email, username) values (6, 'b46da1e1ab99fbb8eba0e535d91d38e72df81a4d023a020f88a2ae08c2e70ec8', 'ividean5@thetimes.co.uk', 'gfolkes5');
insert into users (id, password, email, username) values (7, 'dffeafe4c9c310497e7fa7afd900752195596109d55bf31754b63867ab3f7ec0', 'kslator6@sbwire.com', 'zoury6');
insert into users (id, password, email, username) values (8, '8141b287a3ea2539c846cd17c9444323e3ab10a43eff97a68bb6d935927706ee', 'mswinfon7@360.cn', 'fbankes7');
insert into users (id, password, email, username) values (9, 'd4b6eb145ccb061d0d6ff46e2b2d777ae92b140d89657049ae8b4966b5d2fb21', 'rcrack8@businesswire.com', 'esawood8');
insert into users (id, password, email, username) values (10, 'be8b7fa1251c2d46966c1896818b0490f501966183412fa12c6764a6f5296f2c', 'dprevost9@opensource.org', 'tbus9');

insert into ads (id, description, title, user_id) values (1, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'auctor sed tristique in tempus sit amet sem', 3);
insert into ads (id, description, title, user_id) values (2, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'potenti in eleifend quam a odio', 3);
insert into ads (id, description, title, user_id) values (3, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'lorem vitae mattis nibh ligula', 6);
insert into ads (id, description, title, user_id) values (4, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'at nunc commodo placerat praesent blandit nam', 4);
insert into ads (id, description, title, user_id) values (5, 'Morbi non lectus.', 'ut tellus nulla', 6);
insert into ads (id, description, title, user_id) values (6, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'id massa id nisl', 4);
insert into ads (id, description, title, user_id) values (7, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'ac est lacinia nisi', 3);
insert into ads (id, description, title, user_id) values (8, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'et magnis dis parturient', 4);
insert into ads (id, description, title, user_id) values (9, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'purus aliquet at', 8);
insert into ads (id, description, title, user_id) values (10, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'amet nunc viverra dapibus nulla suscipit', 10);
